version: '2'
services:
    wiki:
        image: requarks/wiki
        environment:
            SESSION_SECRET: ${SESSION_SECRET}
            WIKI_ADMIN_EMAIL: ${WIKI_ADMIN_EMAIL}
            HOST: ${HOST}:${PORT}
            FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
            FACEBOOK_APP_SECRET: ${FACEBOOK_APP_SECRET}
            GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
            GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
        ports:
            - "${PORT}:80"
        volumes:
            - ./config.yml:/var/wiki/config.yml:ro
            - ./wiki-test.pem:/github.pem
        links:
            - wiki-db

    wiki-db:
        image: mongo:latest
        volumes:
            - db_data:/data/db

# We want persistent, anonymous data volumes
volumes:
    db_data:
